debug: true

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
  file: C:/Apigee/micro-services/Work/Azure/pologs/web-portal.log
  #${HOME}\site\wwwroot\pologs\web-portal.log