#spring:
#  oauth2:
 #   client:
  #    clientId: client
   #   clientSecret: secret
    #  accessTokenUri:  http://localhost:8899/userauth/oauth/token
     # userAuthorizationUri: http://localhost:8899/userauth/oauth/authorize
      #clientAuthenticationScheme: form
    #resource:
     #  userInfoUri: http://localhost:8090/
      # preferTokenInfo: false